-- MySQL Script generated by MySQL Workbench
-- Tue Jan  4 23:24:35 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema restaurant_review
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurant_review
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurant_review` DEFAULT CHARACTER SET utf8 ;
USE `restaurant_review` ;

-- -----------------------------------------------------
-- Table `restaurant_review`.`dietary_options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_review`.`dietary_options` (
  `dietary_nameId` INT NOT NULL,
  `dietary_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dietary_nameId`),
  UNIQUE INDEX `dietary_nameId_UNIQUE` (`dietary_nameId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `restaurant_review`.`food_cuisine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_review`.`food_cuisine` (
  `food_cuisineId` INT NOT NULL,
  `cuisine_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`food_cuisineId`),
  UNIQUE INDEX `food_cuisineId_UNIQUE` (`food_cuisineId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `restaurant_review`.`gender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_review`.`gender` (
  `gender_nameId` INT NOT NULL,
  `gender_name` TINYTEXT NOT NULL,
  PRIMARY KEY (`gender_nameId`),
  UNIQUE INDEX `gender_nameId_UNIQUE` (`gender_nameId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `restaurant_review`.`opening_hours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_review`.`opening_hours` (
  `opening_hoursId` INT NOT NULL,
  `opening_hours` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`opening_hoursId`),
  UNIQUE INDEX `opening_hoursId_UNIQUE` (`opening_hoursId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `restaurant_review`.`price_range`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_review`.`price_range` (
  `price_rangeId` INT NOT NULL,
  `price_range` TINYINT NOT NULL,
  PRIMARY KEY (`price_rangeId`),
  UNIQUE INDEX `price_rangeId_UNIQUE` (`price_rangeId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `restaurant_review`.`restaurant_region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_review`.`restaurant_region` (
  `restaurant_regionId` INT NOT NULL,
  `restaurant_region` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`restaurant_regionId`),
  UNIQUE INDEX `restaurant_regionId_UNIQUE` (`restaurant_regionId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `restaurant_review`.`restaurant_rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_review`.`restaurant_rating` (
  `restaurant_ratingId` INT NOT NULL,
  `restaurant_rating` TINYINT NOT NULL,
  PRIMARY KEY (`restaurant_ratingId`),
  UNIQUE INDEX `restaurant_ratingId_UNIQUE` (`restaurant_ratingId` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `restaurant_review`.`restaurant_name`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_review`.`restaurant_name` (
  `restaurantId` INT NOT NULL,
  `restaurant_description` TEXT NOT NULL,
  `restaurant_image` VARCHAR(255) NOT NULL,
  `food_cuisine` INT NOT NULL,
  `dietary_options` INT NOT NULL,
  `hyperlink` VARCHAR(255) NOT NULL,
  `restaurant_hotline` TINYINT NOT NULL,
  `restaurant_region` INT NOT NULL,
  `restaurant_location` VARCHAR(255) NOT NULL,
  `opening_hours` INT NOT NULL,
  `restaurant_rating` INT NOT NULL,
  `price_range` INT NOT NULL,
  PRIMARY KEY (`restaurantId`),
  UNIQUE INDEX `restaurantId_UNIQUE` (`restaurantId` ASC) VISIBLE,
  UNIQUE INDEX `restaurant_image_UNIQUE` (`restaurant_image` ASC) VISIBLE,
  UNIQUE INDEX `hyperlink_UNIQUE` (`hyperlink` ASC) VISIBLE,
  UNIQUE INDEX `restaurant_hotline_UNIQUE` (`restaurant_hotline` ASC) VISIBLE,
  UNIQUE INDEX `restaurant_location_UNIQUE` (`restaurant_location` ASC) VISIBLE,
  INDEX `fkey_food_cuisineId_idx` (`food_cuisine` ASC) VISIBLE,
  INDEX `fkey_dietary_optionsId_idx` (`dietary_options` ASC) VISIBLE,
  INDEX `fkey_restaurant_regionId_idx` (`restaurant_region` ASC) VISIBLE,
  INDEX `fkey_opening_hoursId_idx` (`opening_hours` ASC) VISIBLE,
  INDEX `fkey_restaurant_ratingId_idx` (`restaurant_rating` ASC) VISIBLE,
  INDEX `fkey_price_rangeId_idx` (`price_range` ASC) VISIBLE,
  CONSTRAINT `fkey_food_cuisineId`
    FOREIGN KEY (`food_cuisine`)
    REFERENCES `restaurant_review`.`food_cuisine` (`food_cuisineId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkey_dietary_optionsId`
    FOREIGN KEY (`dietary_options`)
    REFERENCES `restaurant_review`.`dietary_options` (`dietary_nameId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkey_restaurant_regionId`
    FOREIGN KEY (`restaurant_region`)
    REFERENCES `restaurant_review`.`restaurant_region` (`restaurant_regionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkey_opening_hoursId`
    FOREIGN KEY (`opening_hours`)
    REFERENCES `restaurant_review`.`opening_hours` (`opening_hoursId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkey_restaurant_ratingId`
    FOREIGN KEY (`restaurant_rating`)
    REFERENCES `restaurant_review`.`restaurant_rating` (`restaurant_ratingId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkey_price_rangeId`
    FOREIGN KEY (`price_range`)
    REFERENCES `restaurant_review`.`price_range` (`price_rangeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `restaurant_review`.`user_registration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_review`.`user_registration` (
  `userId` INT NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `birthdate` TIMESTAMP(6) NOT NULL,
  `profile_picture` VARCHAR(255) NULL DEFAULT NULL,
  `gender_name` INT NOT NULL,
  `user_address` VARCHAR(255) NULL DEFAULT NULL,
  `mobile_number` TINYINT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `mobile_number_UNIQUE` (`mobile_number` ASC) VISIBLE,
  INDEX `fkey_gender_nameId_idx` (`gender_name` ASC) VISIBLE,
  CONSTRAINT `fkey_gender_nameId`
    FOREIGN KEY (`gender_name`)
    REFERENCES `restaurant_review`.`gender` (`gender_nameId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `restaurant_review`.`user_login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_review`.`user_login` (
  `loginId` INT NOT NULL,
  `userId` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`loginId`),
  UNIQUE INDEX `loginId_UNIQUE` (`loginId` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `fkey_userId_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `fkey_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `restaurant_review`.`user_registration` (`userId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `restaurant_review`.`user_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_review`.`user_review` (
  `user_reviewId` INT NOT NULL,
  `userId` INT NOT NULL,
  `restaurantId` INT NOT NULL,
  `review_content` TEXT NOT NULL,
  `date_posted` TIMESTAMP(6) NOT NULL,
  `user_rating` TINYINT NOT NULL,
  `review_image` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`user_reviewId`),
  UNIQUE INDEX `user_reviewId_UNIQUE` (`user_reviewId` ASC) VISIBLE,
  INDEX `fkey_userId_idx` (`userId` ASC) VISIBLE,
  INDEX `fkey_restaurantId_idx` (`restaurantId` ASC) VISIBLE,
  CONSTRAINT `fkey_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `restaurant_review`.`user_registration` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkey_restaurantId`
    FOREIGN KEY (`restaurantId`)
    REFERENCES `restaurant_review`.`restaurant_name` (`restaurantId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
